### PR TITLE
Features/data aug2

### PR DESCRIPTION
**Pull request by ludovicgirard**
- Move all image transforms to augmentations.py
- data augmentation is now used by default by dcm_dataset

### CODE REVIEW

**Comment by ludovicgirard** [comment]
Just found out Crop doesn't work with dataloader since it does not always produce the same size. Closing for now.

**Comment by igorpontes** [comment]
> Just found out Crop doesn't work with dataloader since it does not always produce the same size. Closing for now.

maybe we could delete Crop, or do a Crop and a zoom after to the original size.
I've just put those transformations but if you guys think that we could add more. I've try some others transformations like add noise, but as it's just one channel image I got some errors.

**Comment by ludovicgirard** [comment]
I just updated Crop so it would always produce the same output size. It should now work with DataLoader. In my opinion that's enough for data augmentations.

**Comment by igorpontes** [comment]
> I just updated Crop so it would always produce the same output size. It should now work with DataLoader. In my opinion that's enough for data augmentations.

parfait!
c'est bien que tu as anullé la transformation pour le jeu de test, comme ça dans le train_test_split, on est capable de faire ça pour le jeu de validation aussi

**Review by igorpontes — APPROVED** [review]

**Pull request merged**
